### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by sherlock-7717** [XiaoDaiGua-Ray/vue3-next-qrcode#1]
目前发现问题：
一、text变更，但不会重新渲染二维码，watchText默认开启，并不生效，
          <Vue3NextQrcode
            watchText
            :size="180"
            :text="codeUrl"
          />
二、如何指定二维码的状态，我看到有重新加载的按钮，但不知如何启用

**Comment by XiaoDaiGua-Ray** [comment]
已修复
